spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

jwt:
  secret: secret123456789
  expiration: 3600000

